In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
melb2 = pd.read_csv("Melbourne01.csv",low_memory=False,on_bad_lines="skip")

In [28]:
melb2.head(30)

,2011,1,1.1,0,4,24.8,0.0,14.0,51,SE,11,13,1007.4,0.0.1
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
3,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
5,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
6,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
7,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
8,2011,1,1.0,0.0,44.0,24.1,0.0,13.3,51.0,ESE,9.0,9.0,1007.3,0.0
9,2011,1,1.0,0.0,54.0,24.3,0.0,13.3,50.0,NE,9.0,9.0,1007.3,0.0
10,2011,1,1.0,0.0,54.0,24.3,0.0,13.3,50.0,NE,9.0,9.0,1007.3,0.0
11,2011,1,1.0,1.0,4.0,24.1,0.0,13.3,51.0,NNE,7.0,7.0,1007.3,0.0
12,2011,1,1.0,1.0,4.0,24.1,0.0,13.3,51.0,NNE,7.0,7.0,1007.3,0.0
13,2011,1,1.0,1.0,14.0,23.5,0.0,13.6,53.0,ENE,7.0,9.0,1007.3,0.0
14,2011,1,1.0,1.0,14.0,23.5,0.0,13.6,53.0,ENE,7.0,9.0,1007.3,0.0
15,2011,1,1.0,1.0,24.0,23.3,0.0,13.5,54.0,ENE,9.0,9.0,1007.3,0.0
16,2011,1,1.0,1.0,24.0,23.3,0.0,13.5,54.0,ENE,9.0,9.0,1007.3,0.0
17,2011,1,1.0,1.0,34.0,23.6,0.0,13.5,53.0,ENE,6.0,7.0,1007.3,0.0
18,2011,1,1.0,1.0,34.0,23.6,0.0,13.5,53.0,ENE,6.0,7.0,1007.3,0.0
19,2011,1,1.0,1.0,34.0,23.6,0.0,13.5,53.0,ENE,6.0,7.0,1007.3,0.0
20,2011,1,1.0,1.0,44.0,23.4,0.0,13.4,53.0,ENE,0.0,0.0,1007.2,0.0
21,2011,1,1.0,2.0,14.0,23.7,0.0,13.8,53.0,ENE,0.0,0.0,1007.3,0.0
22,2011,1,1.0,2.0,14.0,23.7,0.0,13.8,53.0,ENE,0.0,0.0,1007.3,0.0
23,2011,1,1.0,2.0,24.0,23.6,0.0,13.1,51.0,W,0.0,0.0,1007.2,0.0
24,2011,1,1.0,2.0,24.0,23.6,0.0,13.1,51.0,W,0.0,0.0,1007.2,0.0
25,2011,1,1.0,2.0,34.0,23.1,0.0,13.3,54.0,W,0.0,0.0,1007.2,0.0
26,2011,1,1.0,2.0,34.0,23.1,0.0,13.3,54.0,W,0.0,0.0,1007.2,0.0
27,2011,1,1.0,2.0,34.0,23.1,0.0,13.3,54.0,W,0.0,0.0,1007.2,0.0
28,2011,1,1.0,2.0,44.0,22.8,0.0,13.9,57.0,W,0.0,0.0,1007.3,0.0
29,2011,1,1.0,2.0,54.0,22.4,0.0,13.8,58.0,W,0.0,0.0,1007.3,0.0

In [10]:
melb.head(10)

,Year,Month,Day,Hour,Min,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),gamma,Calculated Dew Pt Temp (degrees C),E (hPa),Calculated Apparent Temp (degrees C)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11,13.0,1007.4,0,0.969609267,14.1,15.916676,23.9
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11,11.0,1007.5,0,0.908984645,13.2,14.980401,23.6
2,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11,13.0,1007.5,0,0.915024585,13.2,15.069879,23.7
3,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11,11.0,1007.4,0,0.923559706,13.4,15.201624,23.6
4,2011,1,1.0,0.0,44.0,24.1,0.0,13.3,51.0,ESE,9,9.0,1007.3,0,0.927209422,13.4,15.264860,23.4
5,2011,1,1.0,0.0,54.0,24.3,0.0,13.3,50.0,NE,9,9.0,1007.3,0,0.919542558,13.3,15.145758,23.5
6,2011,1,1.0,1.0,4.0,24.1,0.0,13.3,51.0,NNE,7,7.0,1007.3,0,0.927209422,13.4,15.264860,23.8
7,2011,1,1.0,1.0,14.0,23.5,0.0,13.6,53.0,ENE,7,9.0,1007.3,0,0.92916463,13.5,15.302266,23.2
8,2011,1,1.0,1.0,24.0,23.3,0.0,13.5,54.0,ENE,9,9.0,1007.3,0,0.935651687,13.6,15.404350,22.6
9,2011,1,1.0,1.0,34.0,23.6,0.0,13.5,53.0,ENE,6,7.0,1007.3,0,0.935260646,13.6,15.394580,23.5

In [11]:
melb.tail(20)

,Year,Month,Day,Hour,Min,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),gamma,Calculated Dew Pt Temp (degrees C),E (hPa),Calculated Apparent Temp (degrees C)
505335,2022,3,8.0,12.0,50.0,19.4,16.4,12.4,64.0,S,39,43.0,1018.2,0,0.86402316,12.5,14.381803,12.6
505336,2022,3,8.0,13.0,20.0,19.2,16.8,12.7,66.0,SSW,39,43.0,1018.1,0,0.882225021,12.7,14.648018,12.5
505337,2022,3,8.0,13.0,30.0,19.2,16.4,12.5,65.0,S,37,41.0,1018.1,0,0.866957549,12.5,14.426078,12.8
505338,2022,3,8.0,13.0,40.0,19.4,17.2,12.2,63.0,S,35,41.0,1018.0,0,0.848274803,12.2,14.157088,13.3
505339,2022,3,8.0,13.0,50.0,19.8,17.9,13.0,65.0,S,37,44.0,1018.1,0,0.904612476,13.1,14.973333,13.5
505340,2022,3,8.0,14.0,0.0,19.2,17.3,12.9,67.0,SSW,37,43.0,1018.0,0,0.897262898,13,14.869957,12.9
505341,2022,3,8.0,14.0,10.0,19.3,17.3,12.6,65.0,S,35,41.0,1018.0,0,0.873244721,12.6,14.516053,13.3
505342,2022,3,8.0,14.0,20.0,19.3,18.2,13.2,68.0,S,39,48.0,1017.9,0,0.918365156,13.3,15.186025,12.7
505343,2022,3,8.0,14.0,30.0,19.1,16.9,13.3,69.0,S,33,41.0,1017.9,0,0.920385059,13.3,15.218843,13.7
505344,2022,3,8.0,14.0,40.0,19.1,16.0,13.5,70.0,SSW,39,48.0,1017.8,0,0.934773796,13.5,15.439405,12.6
505345,2022,3,8.0,14.0,50.0,19.2,17.4,13.2,68.0,S,39,43.0,1017.9,0,0.912077984,13.2,15.091897,12.6
505346,2022,3,8.0,15.0,0.0,18.9,16.6,13.1,69.0,S,39,48.0,1017.8,0,0.907787934,13.1,15.030400,12.3
505347,2022,3,8.0,15.0,10.0,18.9,15.8,13.3,70.0,S,30,37.0,1017.8,0,0.922176672,13.4,15.248232,14.1
505348,2022,3,8.0,15.0,20.0,18.7,15.1,13.1,70.0,S,35,44.0,1017.9,0,0.90956128,13.2,15.059133,12.9
505349,2022,3,8.0,15.0,30.0,18.7,16.7,13.8,73.0,S,28,33.0,1017.9,0,0.951525479,13.8,15.704524,14.4
505350,2022,3,8.0,15.0,40.0,18.6,16.0,13.2,71.0,SSW,39,46.0,1018.0,0,0.917431356,13.3,15.179146,12
505351,2022,3,8.0,15.0,50.0,18.7,18.5,13.6,72.0,SSW,35,46.0,1017.9,0,0.937732157,13.6,15.489394,13
505352,2022,3,8.0,16.0,0.0,18.9,17.6,13.7,72.0,SSW,35,41.0,1017.8,0,0.950347549,13.8,15.683896,13.3
505353,2022,3,8.0,16.0,10.0,19.2,18.3,13.8,71.0,S,32,35.0,1017.8,0,0.955250156,13.9,15.757716,14.2
505354,2022,3,8.0,16.0,20.0,19.2,17.5,13.6,70.0,S,28,32.0,1017.7,0,0.941065521,13.6,15.535776,14.9

In [12]:
melb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505355 entries, 0 to 505354
Data columns (total 18 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Year                                  505222 non-null  object
 1   Month                                 504739 non-null  object
 2   Day                                   504723 non-null  float64
 3   Hour                                  504723 non-null  float64
 4   Min                                   504723 non-null  float64
 5   Air Temp (degrees C)                  504723 non-null  float64
 6   Apparent Temp (degrees C)             504723 non-null  float64
 7   Dew Pt Temp (degrees C)               504723 non-null  float64
 8   Humidity (%)                          504723 non-null  float64
 9   Wind Direction                        504723 non-null  object
 10  Wind Speed (km/h)                     504723 non-null  object
 11  Wind Gust  (km/h)                     504723 non-null  float64
 12  MSLP (hPa)                            504723 non-null  float64
 13  Rainfall since 9 am (mm)              504723 non-null  object
 14  gamma                                 505355 non-null  object
 15  Calculated Dew Pt Temp (degrees C)    505355 non-null  object
 16  E (hPa)                               505355 non-null  float64
 17  Calculated Apparent Temp (degrees C)  505355 non-null  object
dtypes: float64(10), object(8)
memory usage: 69.4+ MB

In [13]:
melb.describe()

,Day,Hour,Min,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Gust (km/h),MSLP (hPa),E (hPa)
count,504723.000000,504723.000000,504723.000000,504723.000000,504723.000000,504723.000000,504723.000000,504723.000000,504723.000000,505355.000000
mean,15.740000,11.443412,26.288140,15.972608,12.087050,9.055060,66.386806,22.521205,1016.303049,11.858907
std,8.818064,6.883219,17.197089,5.624138,7.203826,4.086159,17.756705,23.646415,74.033126,3.464860
min,1.000000,0.000000,0.000000,0.000000,-4.100000,-8.700000,-1.000000,-9999.000000,-9999.000000,-0.422872
25%,8.000000,5.000000,10.000000,12.100000,7.600000,6.100000,55.000000,13.000000,1012.100000,9.366169
50%,16.000000,11.000000,25.000000,15.300000,11.800000,8.600000,67.000000,20.000000,1017.300000,11.132322
75%,23.000000,17.000000,40.000000,19.200000,16.600000,11.700000,79.000000,30.000000,1022.400000,13.700759
max,31.000000,23.000000,59.000000,43.500000,43.300000,36.900000,100.000000,109.000000,1039.000000,62.165716

In [15]:
melb.shape

(505355, 18)

In [18]:
adel = pd.read_csv("Adelaide01.csv", low_memory=False)

In [19]:
adel.head(10)

,2015,08,15,09,00,12.2,11.2,11,92,N,9,13,1032.7,1.4
0,2015,8,15,9,30,12.9,11.8,10.6,86.0,N,11.0,13.0,1032.9,0
1,2015,8,15,10,0,12.9,11.8,10.8,87.0,N,11.0,17.0,1032.9,0
2,2015,8,15,10,30,13.6,12.5,10.7,82.0,NW,15.0,17.0,1032.9,0
3,2015,8,15,11,0,13.5,12.3,10.2,80.0,NW,13.0,17.0,1032.7,0
4,2015,8,15,11,30,14.1,12.9,10.2,77.0,WNW,13.0,15.0,1032.6,0
5,2015,8,15,12,0,14.2,12.8,9.5,73.0,WNW,15.0,19.0,1032.5,0
6,2015,8,15,12,30,13.8,12.5,9.9,77.0,WNW,15.0,19.0,1032.2,0
7,2015,8,15,13,0,13.5,12.1,11.0,85.0,W,17.0,19.0,1031.7,0
8,2015,8,15,13,30,13.3,12.1,10.2,81.0,W,13.0,17.0,1031.4,0
9,2015,8,15,14,0,13.3,11.8,10.4,82.0,WSW,13.0,17.0,1031.4,0

In [20]:
melb.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Min', 'Air Temp (degrees C)',
       'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)', 'Humidity (%)',
       'Wind Direction', 'Wind Speed (km/h)', 'Wind Gust  (km/h)',
       'MSLP (hPa)', 'Rainfall since 9 am (mm)', 'gamma',
       'Calculated Dew Pt Temp (degrees C)', 'E (hPa)',
       'Calculated Apparent Temp (degrees C)'],
      dtype='object')

In [31]:
melb2.columns = ['Year', 'Month', 'Day', 'Hour', 'Min', 'Air Temp (degrees C)',
       'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)', 'Humidity (%)',
       'Wind Direction', 'Wind Speed (km/h)', 'Wind Gust  (km/h)',
       'MSLP (hPa)', 'Rainfall since 9 am (mm)']

In [32]:
melb2.head(20)

,Year,Month,Day,Hour,Min,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
3,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
5,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
6,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
7,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
8,2011,1,1.0,0.0,44.0,24.1,0.0,13.3,51.0,ESE,9.0,9.0,1007.3,0.0
9,2011,1,1.0,0.0,54.0,24.3,0.0,13.3,50.0,NE,9.0,9.0,1007.3,0.0
10,2011,1,1.0,0.0,54.0,24.3,0.0,13.3,50.0,NE,9.0,9.0,1007.3,0.0
11,2011,1,1.0,1.0,4.0,24.1,0.0,13.3,51.0,NNE,7.0,7.0,1007.3,0.0
12,2011,1,1.0,1.0,4.0,24.1,0.0,13.3,51.0,NNE,7.0,7.0,1007.3,0.0
13,2011,1,1.0,1.0,14.0,23.5,0.0,13.6,53.0,ENE,7.0,9.0,1007.3,0.0
14,2011,1,1.0,1.0,14.0,23.5,0.0,13.6,53.0,ENE,7.0,9.0,1007.3,0.0
15,2011,1,1.0,1.0,24.0,23.3,0.0,13.5,54.0,ENE,9.0,9.0,1007.3,0.0
16,2011,1,1.0,1.0,24.0,23.3,0.0,13.5,54.0,ENE,9.0,9.0,1007.3,0.0
17,2011,1,1.0,1.0,34.0,23.6,0.0,13.5,53.0,ENE,6.0,7.0,1007.3,0.0
18,2011,1,1.0,1.0,34.0,23.6,0.0,13.5,53.0,ENE,6.0,7.0,1007.3,0.0
19,2011,1,1.0,1.0,34.0,23.6,0.0,13.5,53.0,ENE,6.0,7.0,1007.3,0.0

In [34]:
melb2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1113151 entries, 0 to 1113150
Data columns (total 14 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Year                       1113151 non-null  object
 1   Month                      1112535 non-null  object
 2   Day                        1112519 non-null  float64
 3   Hour                       1112519 non-null  float64
 4   Min                        1112519 non-null  float64
 5   Air Temp (degrees C)       1112519 non-null  float64
 6   Apparent Temp (degrees C)  1112519 non-null  float64
 7   Dew Pt Temp (degrees C)    1112519 non-null  float64
 8   Humidity (%)               1112519 non-null  float64
 9   Wind Direction             1112519 non-null  object
 10  Wind Speed (km/h)          1112519 non-null  float64
 11  Wind Gust  (km/h)          1112519 non-null  float64
 12  MSLP (hPa)                 1112519 non-null  float64
 13  Rainfall since 9 am (mm)   1112519 non-null  object
dtypes: float64(10), object(4)
memory usage: 118.9+ MB

In [35]:
# change the day, hour, min datatypes
# concatenate the time components together and put into datetime type
# add to new dataframe?

# start doing EDA
    # Add to the Github